name: Pella Free 指定账号执行

on:
  schedule:
    - cron: '45 3 * * *'  # 每天北京时间 11:45 运行
  workflow_dispatch:
    inputs:
      account_name:
        description: '指定账号邮箱（留空运行全部）'
        required: false
        default: ''
        type: string

concurrency:
  group: PellaFree_Renew
  cancel-in-progress: false

permissions:
  contents: read
  actions: write

jobs:
  renew:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取私有仓库
        uses: actions/checkout@v4
        with:
          repository: oyz6/scripts
          token: ${{ secrets.REPO_TOKEN }}
          path: .  # 拉到根目录
      
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: 安装 Chrome 浏览器
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: 安装 Python 依赖
        run: pip install selenium==4.15.0 requests==2.31.0 webdriver-manager==4.0.1
      
      - name: 运行续期脚本
        env:
          PELLA_ACCOUNTS: ${{ secrets.PELLA_ACCOUNTS }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          ACCOUNT_NAME: ${{ github.event.inputs.account_name }}
        run: python scripts/PellaFree/PellaFree_Renew.py
#        > /dev/null 2>&1
#      - name: 上传截图
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: screenshots-${{ github.run_number }}
#          path: output/screenshots/
#          retention-days: 3
      
      - name: 清理历史运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: ${{ github.workflow }}
          retain_days: 0
          keep_minimum_runs: 3
